#!/bin/bash

export PACKAGE_CORE_NAME="pingu"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION=v0.0.4-alpha
export PACKAGE_CORE_ORG="sheepla"

export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/${PACKAGE_CORE_ORG}/pingu/releases/download"
