#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local os="$PACKAGE_OS"
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  #
  case $platform in
  darwin)
    platform="Darwin"
    ;;
  linux)
    platform="Linux"
  ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  case $arch in
  arm64) ;;

  amd64)
    arch="x86_64"
    ;;
  *)
    log::error "[$(timestamp)] unsupport arch: $arch"
    return 1
    ;;
  esac
  #

  # files
  local tmp_file="$name.tar.gz"
  local source_bin_file="./$name"
  # local target_bin_file="$usr_bin_dir/$name"

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/sheepla/pingu/releases
  # example:
  #   https://github.com/sheepla/pingu/releases/download/v0.0.4-alpha/pingu_0.0.4-alpha_Darwin_arm64.tar.gz
  #   https://github.com/sheepla/pingu/releases/download/v0.0.4-alpha/pingu_0.0.4-alpha_Darwin_x86_64.tar.gz
  #   https://github.com/sheepla/pingu/releases/download/v0.0.4-alpha/pingu_0.0.4-alpha_Linux_arm64.tar.gz
  #   https://github.com/sheepla/pingu/releases/download/v0.0.4-alpha/pingu_0.0.4-alpha_Linux_x86_64.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/$PACKAGE_CORE_VERSION/${name}_${PACKAGE_CORE_VERSION#v}_${platform}_${arch}.tar.gz"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  os::install $source_bin_file $usr_bin_dir $name

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
